experiment:
  id: 'baseline'
  sequences: [[A, D, B, E], [F, D, B, C]]
#  sequences: [['A', 'C', 'B'], ['D', 'C', 'B'], ['C', 'B', 'A'], ['B', 'D', 'A']]
#  sequences: [['A', 'C', 'B'], ['D', 'C', 'B']]
#  sequences: [['A', 'B', 'C']]
#  sequences: [['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U']]
  runtime: null
  episodes: 100
  run_add_calib: False
  save_final: False
  save_auto: False
  save_auto_epoches: 5
  generate_rand_seed_offset: False
  seed_offset: null
  log_weights: True
  log_permanence: True
plotting:
  size: [10, 12]
  file_type: 'pdf'
  save_figure: True
performance:
  compute_performance: True
  method: "all_symbols"
  running_avgs: [ 0.25, 0.5, 0.75, 1.0 ]
network:
  num_symbols: 6
  num_neurons: 15
  pattern_size: 3
backend:
  module_name: "nestml_mc01_module"
  neuron_name: "iaf_psc_exp_nonlineardendritemc01_nestml"
encoding:
  dt_stm: 40
  dt_seq: 100
  t_exc_start: 30
  t_scaling_factor: 1.
  num_repetitions: 1
plasticity:
#  type: 'original'
#  type: 'bss2'
  type: 'bss2'
  learning_factor: 1    # 2 for int
  weight_learning: False
  weight_learning_scale: 0.0026
  permanence_init_min: 0
  permanence_init_max: 8
  permanence_max: 20.
  permanence_threshold: 10.
  correlation_threshold: 0.0005 # 0.06 for tau_+ = 20
  w_mature: 0.1298
  y: 1
  lambda_plus: 0.06   # 0.25 for int
  lambda_minus: 0.0005    # 0.0007 for int
  lambda_h: 0.024        # 0.03 for int
  homeostasis_depression_rate: 1.0
  target_rate_h: 0.16   # 0.14 for int
  tau_plus: 19      # 20 for int
  tau_h: null       # computed during runtime based on sequence length
  delta_t_min: 4
  delta_t_max: 75
  dt: 0.1
neurons:
  inhibitory:
    c_m: 250.e-3      # nF in pyNN, pF in nest -> * 1/1000
    v_rest: 0
    v_reset: 0
    v_thresh: 15
    tau_m: 5
    tau_syn_I: 1.0
    tau_syn_E: 0.5
    tau_refrac: 2
  excitatory:
    c_m: 250
    v_rest: 0
    v_reset: 0
    v_thresh: 20
    tau_m: 10
    tau_syn_ext: 2
    tau_syn_den: 5
    tau_syn_inh: 1
    tau_refrac: 10
  dendrite:
    I_p: 200
    tau_dAP: 60
    theta_dAP: 59
synapses:
  dyn_inh_weights: False
  dyn_weight_calculation: True
  w_exc_inh_dyn: null
  w_ext_exc: 4.1122
  w_exc_exc: 0.0e-3
  w_exc_inh: 3.8747
  w_inh_exc: 12.9155
  p_exc_exc: 0.2
  receptor_ext_exc: "I_1"
  receptor_exc_exc: "I_2"
  receptor_exc_inh: "excitatory"
  receptor_inh_exc: "I_3"
  delay_ext_exc: 0.1
  delay_exc_exc: 2
  delay_exc_inh: 0.1
  delay_inh_exc: 0.1
  j_ext_exc_psp: 1.1 * NetworkParameters.Neurons.Excitatory.v_thresh
  j_exc_inh_psp: 1.2 * NetworkParameters.Neurons.Inhibitory.v_thresh / NetworkParameters.Network.pattern_size
  j_inh_exc_psp: -2 * NetworkParameters.Neurons.Excitatory.v_thresh